apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

resources:
  - ../../base/namespace.yaml
  - ../../base/postgresql.yaml
  - ../../base/powerdns-config.yaml
  - ../../base/pdb.yaml
  - powerdns-deployment.yaml
  - services.yaml
  - firewall-configmap.yaml

commonLabels:
  deployment-scenario: nodeport
  app.kubernetes.io/part-of: dns-infrastructure
