$ANSIBLE_VAULT;1.1;AES256
31636365363230623830653265393733353564643336373864613530346137313662663538616135
6266383263393535333230616664363361666366363464620a396138646564376661336231663366
36643062383739386364656338313034613364323065663263353966633663356331313936383535
3065393833643765300a616564373031343263333337353936666338656635643562313063666162
64306363316361356466316232613439393733376261326136633939373765616136326138386164
63616636303662666634616162643538303638653261373465306131633630386663316133303634
64353534313333636139626239613537646337346163313034323263656262653439633537333630
32343063373439373166363935346566356364653432656165656262313566623562613337386563
34383765613632306536623834336230653536373962653465653366326330623463643036666239
33653137636463373833323063376638333861653637316161386534326462323563663936626633
386261396131343631353834313066343239
