apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: argocd-letsencrypt-issuer
spec:
  acme:
    email: ldamasio@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: argocd-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "argocd-letsencrypt-issuer"
    traefik.ingress.kubernetes.io/router.tls: "true"
    # ArgoCD needs special handling for gRPC
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - argocd.robson.rbx.ia.br
    secretName: argocd-server-tls
  rules:
  - host: argocd.robson.rbx.ia.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80

