apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbs-backend-nginx-prod-ingress
  namespace: robson
  annotations:
    cert-manager.io/cluster-issuer: "rbs-backend-prod-clusterissuer"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - api.robson.rbx.ia.br
    secretName: rbs-backend-nginx-prod-tls
  rules:
  - host: api.robson.rbx.ia.br
    http:
      paths:
      - pathType: Prefix
        path: "/static"
        backend:
          service:
            name: rbs-backend-nginx-prod-svc
            port:
              number: 80

