apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbs-frontend-prod-ingress
  namespace: robson
  annotations:
    cert-manager.io/cluster-issuer: "rbs-frontend-prod-clusterissuer"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - app.robson.rbx.ia.br
    secretName: rbs-frontend-prod-tls
  rules:
  - host: app.robson.rbx.ia.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rbs-frontend-prod-svc
            port:
              number: 80

