apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rbs-backend-nginx-prod-clusterissuer
spec:
  acme:
    email: ldamasio@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: rbs-backend-nginx-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: traefik
