apiVersion: v1
kind: Secret
metadata:
  name: rbs-paradedb-secret
  namespace: robson
  labels:
    app: rbs-paradedb
type: Opaque
stringData:
  POSTGRES_USER: robson
  POSTGRES_PASSWORD: RbsParade2024Secure!
  POSTGRES_DB: rbsdb

