apiVersion: v1
kind: Service
metadata:
  name: rbs-frontend-prod-svc
  namespace: robson
spec:
  selector:
    app: rbs-frontend-prod-deploy
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
