apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rbxsystems-ch-prod-clusterissuer
spec:
  acme:
    email: ldamasio@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: rbxsystems-ch-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: traefik
